plugins {
    id 'application'
    id 'org.openjfx.javafxplugin' version '0.1.0'
    id 'org.beryx.jlink' version '3.1.1'
}

group = 'dev.mapz'
version = '0.1.0'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

javafx {
    version = '21.0.5'
    modules = [ 'javafx.controls', 'javafx.graphics' ]
}

application {
    mainModule = 'dev.mapz.launcher'
    mainClass = 'dev.mapz.launcher.LauncherApp'
}

jlink {
    options = [
        '--strip-debug',
        '--compress', '2',
        '--no-header-files',
        '--no-man-pages'
    ]

    launcher {
        name = 'mapz-launcher'
    }

    jpackage {
        imageName = 'mapz-launcher'
        installerName = 'mapz-launcher'
        installerType = 'exe'
        appVersion = '0.1.0'
        vendor = 'mapz'
        description = 'The _mapz Minecraft launcher'
        installerOptions = [
            '--win-menu',
            '--win-menu-group', 'mapz',
            '--win-shortcut',
            '--win-shortcut-prompt'
        ]
    }
}

jar {
    manifest {
        attributes 'Main-Class': application.mainClass.get()
    }
}
